### ISSUE TITLE
Using INPUT_MODEL_ENTITYNAME is not working

### ISSUE THREAD

**Issue by stefanhenz** [JumpMind/metl#817] opened 2018-02-12 12:32 UTC
Hi

I'm using metl for importing bulk-data over a rdms-reader to a rdms-writer in a new database structure.

My Flow:
_start->RDBMS-Reader [Getting every registered kpi] -> (passing list with kpis.kpi_id,kpis.name) -> RDBMS-Reader [Getting sensors data kpis.name]-> (passing list with kpis.kpi-id, value,date) -> RDBMS-Writer ]insert in to database[-> End_

In the documentation I found the possibility to use values of the INPUT-Model as parameter in a query. 

```
_select ...
   field3=:INPUT_MODEL_ENTITY_NAME.INPUT_MODEL_ATTRIBUTE_NAME_
```

I looked in the documentation and included the statement in my code. 

```
select 
:kpis.id /* kpi_measurements.kpi_id */
, start_time  /* kpi_measurements.timestamp */
, trim(substr(perfdata,locate('=',perfdata)+1)) /* kpi_measurements.value */
from icinga_servicechecks,icinga_objects
where icinga_servicechecks.service_object_id=icinga_objects.object_id
and icinga_objects.is_active = 1
and icinga_objects.name1 like 'usv101%'
and icinga_objects.name2 like '%output%load%'
and start_time>= Date_ADD('$(_date) $(_startTime)', INTERVAL -$(Intervall_Import) MINUTE)
and start_time <= '$(_date) $(_startTime)'
```

I get the following error:
`org.springframework.dao.InvalidDataAccessApiUsageException: No value supplied for the SQL parameter 'kpis.id': No value registered for key 'kpis.id'`

Could provide me a working example?

Best regards

Stefan

**Comment by nrichardson99** [comment] 2018-02-12 12:39
Hi Stefan,
In the Model coming out of the first RDBMS Reader is the Entity name 'kpis' and the attribute name 'id'?

In the second RDBMS Reader the reference to the Input Model must match the entity.attribute name exactly as it appears in the model.  In your comment _(passing list with kpis.kpi_id,kpis.name)_ it appears the attribute name might be kpi_id instead of just id.

**Comment by stefanhenz** [comment] 2018-02-12 13:16
Hi 

oops there was a mistake in my first description of the flow. 

start->RDBMS-Reader [Getting every registered kpi] -> (passing list with kpis.**id**,kpis.name) -> RDBMS-Reader [Getting sensors data kpis.name]-> (passing list with kpis.kpi-id, value,date) -> RDBMS-Writer ]insert in to database[-> End

This is the first query where I write to  the output modell:

select kpis.id /* kpis.id */,
sensors.name /* sensors.name */,
kpis.name /* kpis.name */
from sensors, 
kpis where sensors.kpi_id=kpis.id
and kpis.type='usv'

As far as I can see it should be the same. Sorry, that was a mistake of mine. 
The output-modell of Query 1 -> is exactly the input Model of Query 2.

![image](https://user-images.githubusercontent.com/33940613/36098284-ae66b042-0ffe-11e8-8197-20417d39b820.png)

So if this should work as written in the documentation my query should work?

If I try this with kpis.name as condition for the query I get the same error: 
and icinga_objects.name1 = ':kpis.name'

Any clue?

Best regards 

Stefan

**Comment by nrichardson99** [comment] 2018-02-12 13:22
Check the second RDBMS Reader setting for 'Run When'.  It needs to be PER MESSAGE if you are wanting to run per message that is passed into it.

**Comment by stefanhenz** [comment] 2018-02-12 13:34
ok, changed but no effect. If I put an "message logger" in between. I got one Message.

![image](https://user-images.githubusercontent.com/33940613/36099038-867a6ae4-1001-11e8-90c3-b34a67b7fe6e.png)

I'm using the keys in the  key -> "kpis.id" as you can see in the printscreen.

![image](https://user-images.githubusercontent.com/33940613/36099097-bf2c3304-1001-11e8-89f3-a93af7edfe7e.png)

Thanks for your help.

Stefan

**Comment by nrichardson99** [comment] 2018-02-12 13:36
Your error now shows it is looking for a parameter of kpis.kpi_id instead of kpis.id.  Did you change your sql to be :kpis.kpi_id?

**Comment by stefanhenz** [comment] 2018-02-12 13:41
Ok - got the point. changed to the value in the json-array. But
![image](https://user-images.githubusercontent.com/33940613/36099364-acdae24e-1002-11e8-9bbb-0a51fe836b9f.png)

Still the same error.

**Comment by nrichardson99** [comment] 2018-02-12 13:55
Two things, 
1. Could you export your Melt Flow and attach it so I could import and look at it here.
 (Highlight your Flow and select File -> Export)
![image](https://user-images.githubusercontent.com/14093056/36099916-573dc962-0fd2-11e8-89d1-c2fc2c8399c1.png)

2. Take a look at one of the Sample Project flows that comes with Metl by default.  It has an example of the scenario you are trying to accomplish.  Look through all the settings on the second reader component to make sure yours match.  
Project - Enhance Entities using Rdbms Reader 
![image](https://user-images.githubusercontent.com/14093056/36099772-d47063aa-0fd1-11e8-8554-4d10791a48bc.png)

**Comment by stefanhenz** [comment] 2018-02-12 14:01
Hi
Attached you find the export of the Flow. I'm gonna check your example. It looks pretty straight forward to me.

[flow.zip](https://github.com/JumpMind/metl/files/1716486/flow.zip)

**Comment by nrichardson99** [comment] 2018-02-12 18:41
Thanks, I was able to replicate the issue and have found where the bug occurs.  We are working to get it resolved in our next 3.0.1 release hopefully this week.

**Comment by nrichardson99** [comment] 2018-02-13 09:19
Stefan, 
After re-looking at your flow I now realize the way you are using the RDBMS Reader isn't quite the way it was intended and this doesn't appear to be a bug.  When using two readers where the second one is run based on criteria from the first, the concept is that the second query would have a 'WHERE xxxx IN (:entity.attribute)' condition and the component would be Run When 'PER MESSAGE' so the sql would take every message read in, create a list of values from the input message and put them into an 'IN' list and run the second sql based on that condition.  The intent isn't to put any of these input values in the SELECT part.  If you need to maintain additional fields in your flow then you should add components to the flow to lookup or merge your data outside these two RDBMS Reader components.

From the scenario you provided, I think I understand what you are doing now and it makes sense, however let me share a couple alternatives to how you have it set up.

Your first reader appears to be functioning as both a lookup and a filter for the second query. (Not sure  what/how you plan to use sensors.name from the first sql so this may impact the approach you choose)

Take a look through these and see if this makes sense and if you'd be able to use one.
1. If you can, reduce your SQL to one RDBMS Reader and do your joins there to output all the fields you need at once.  Optimally let your database do the work for you if you can.

Each of the below would have different impacts depending on what you need as an outcome as well as the volume of data you are processing so you may have to try a couple depending on your scenario.

2. Use a Lookup component.  If you only need to attach the id back to the data pulled in the second query then add a lookup component that is fed into by both of your RDBMS Readers.  You'll have to adjust your model to have all 4 fields, id, name, timestamp and value.  One input has just id and name, second input has name, timestamp and value.  Lookup on name fill in the id.  Then you could map back to another model where your entity only has the three fields on your table.
![image](https://user-images.githubusercontent.com/14093056/36141506-eec22c88-1072-11e8-94f7-25e511b4b7f0.png)

3. Use a Merge component.  Similar to #2 use a Merge where both readers flow into it and combine the data on the name.  Then if there are cases where there are id/name records without a row from the second output you could filter these out after the merge by using a content router and only route where the timestamp or value is not null.
![image](https://user-images.githubusercontent.com/14093056/36141679-a8b797a4-1073-11e8-8a10-bb931404bde0.png)

4. Use a Temp RDBMS component.  Run both SQL independently, simulating two 'temp tables' (from two RDBMS Readers as you have) into the Temp RDBMS and then write a single query joining these new 'temp tables' results inside it.
![image](https://user-images.githubusercontent.com/14093056/36141820-301478b6-1074-11e8-8cba-f66c5e853773.png)

There are other ways as well, but hopefully this will get you moving again.
Thanks,
-Nathan

**Comment by stefanhenz** [comment] 2018-02-14 08:46
Dear Nathan

Thank you very much for your detailed response. We appreciate your proposals and we have a running solution based on suggestion 4. 

Thanks, 
- Stefan

**Closed** 2018-02-14 11:39 UTC
