### ISSUE TITLE
Clean up temp files.

### ISSUE THREAD

**Issue by abrougher** [JumpMind/metl#497] opened 2016-09-20 14:41 UTC
There's a list of large files being added to the ./metl/tmp directory that should be cleaned up.

Work around is to delete these files manually.

Example:
126972  /opt/metl/tmp/jetty-0.0.0.0-42000-metl.war-_metl-any-7577103135488313352.dir
126972  /opt/metl/tmp/jetty-0.0.0.0-42000-metl.war-_metl-any-517283273772929159.dir
126968  /opt/metl/tmp/jetty-0.0.0.0-42000-metl.war-_metl-any-7577103135488313352.dir/webapp
126968  /opt/metl/tmp/jetty-0.0.0.0-42000-metl.war-_metl-any-517283273772929159.dir/webapp
125604  /opt/metl/tmp/jetty--42000-metl-1.3.1.r37.war-_metl-any-8840120448924702421.dir
125604  /opt/metl/tmp/jetty--42000-metl-1.3.1.r37.war-_metl-any-8252283311073076455.dir
125604  /opt/metl/tmp/jetty--42000-metl-1.3.1.r37.war-_metl-any-823160375400044962.dir
125604  /opt/metl/tmp/jetty--42000-metl-1.3.1.r37.war-_metl-any-7713271036555041552.dir
125604  /opt/metl/tmp/jetty--42000-metl-1.3.1.r37.war-_metl-any-7587657870628536103.dir

**Comment by chenson42** [comment] 2016-09-26 19:00
Dupe of #513

**Closed by chenson42** 2016-09-26 19:00 UTC
Labels: enhancement
